import { useRef, useCallback, useEffect, useState } from 'react';
import { createPortal } from 'react-dom';
import { useSessionStore, useCurrentSession } from '@/stores/sessionStore';
import { useWorkerStore } from '@/stores/workerStore';
import { useUIStore } from '@/stores/uiStore';
import { useAdapterStore } from '@/stores/adapterStore';
import { useQueueStore } from '@/stores/queueStore';
import { useMediaQuery } from '@/hooks/useMediaQuery';
import { SendQueuePanel } from '@/components/chat/SendQueuePanel';
import { SettingsPopover } from '@/components/chat/SettingsPopover';
import { ModelSelect } from '@/components/ui/ModelSelect';
import { DirectoryInput } from '@/components/session/DirectoryInput';
import { Modal } from '@/components/ui/Modal';
import {
  RichTextComposer,
  type ComposerValue,
  type RichTextComposerHandle,
} from '@/components/chat/RichTextComposer';
import {
  fetchDirectories,
  registerServerFileAttachment,
  uploadSessionAttachment,
} from '@/services/api';
import { attachmentMarkdown, serverFileDownloadHref } from '@/utils/attachmentMarkdown';
import {
  isAttachmentPayloadForSession,
  type PanAttachmentPayload,
  writePanAttachmentPayload,
} from '@/utils/attachmentPayload';
import {
  isMockMode,
  mockRegisterServerFileAttachment,
  mockUploadSessionAttachment,
} from '@/demo/mockBackend';
import { directoryEntryExists, parentDirectory } from '@/utils/directoryInput';
import {
  ChevronDown,
  ChevronUp,
  CornerUpRight,
  Expand,
  File as FileIcon,
  Minimize2,
  Paperclip,
  Settings,
  X,
} from 'lucide-react';
import type { AdapterConfig, MessagePart, PermissionMode } from '@/types';
import type { AttachmentLocation } from '@/types/attachment';

const PILL_CLASS =
  'inline-flex items-center gap-1 px-2 py-1 text-xs rounded-md border border-border-default bg-bg-tertiary hover:bg-bg-hover cursor-pointer transition-colors';

const DROPDOWN_ITEM = 'px-2 py-1 text-xs hover:bg-bg-hover cursor-pointer whitespace-nowrap';

// ── helpers ──

function supportsSetting(config: AdapterConfig | null, name: string): boolean {
  if (!config?.supportedSettings) return false;
  return config.supportedSettings.includes(name);
}

function permBorderClass(value: string): string {
  if (value === 'bypass') return 'border-danger/50';
  if (value === 'yolo' || value === 'acceptEdits') return 'border-warning/50';
  return 'border-border-default';
}

type AttachmentStatus = 'uploading' | 'registering' | 'ready' | 'error';

interface PendingAttachment {
  /** UI occurrence identity. Multiple occurrences may share attachmentId. */
  occurrenceId: string;
  /** Compatibility alias used by the existing chip/test selectors. */
  id: string;
  /** Original/user-facing filename. Never derive the label from path. */
  displayName: string;
  /** Legacy local path used for dedupe/title; not the Markdown label. */
  path?: string;
  /** Safe href generated by the server or the fs download route. */
  href?: string;
  file?: File;
  status: AttachmentStatus;
  loadedBytes?: number;
  totalBytes?: number;
  fileKey?: string;
  error?: string;
  /** Server-owned opaque id used in structured message parts. */
  attachmentId?: string;
  mimeType?: string;
  source?: 'upload' | 'server_file';
  location?: AttachmentLocation;
}

function attachmentId(): string {
  if (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function') {
    return crypto.randomUUID();
  }
  return `${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`;
}

function clientFileKey(file: File): string {
  return `${file.name}\u0000${file.size}\u0000${file.lastModified}`;
}

function uploadAttachmentIdFromHref(href: string | undefined): string | undefined {
  const match = href?.match(
    /\/api\/attachments\/(upload_[A-Za-z0-9]{32}(?:\.[A-Za-z0-9._-]{1,32})?)/,
  );
  return match?.[1];
}

function attachmentOccurrenceId(attachment: PendingAttachment): string {
  return attachment.occurrenceId || attachment.id;
}

interface SendSnapshot {
  transactionId: string;
  clientMessageId: string;
  sessionId: string;
  value: ComposerValue;
  attachments: PendingAttachment[];
  message: string;
  parts?: MessagePart[];
}

function composerPartOccurrenceId(part: ComposerValue['parts'][number]): string | null {
  return part.type === 'attachment' ? part.occurrenceId || part.attachmentId : null;
}

function emptyComposerValue(): ComposerValue {
  return {
    parts: [{ type: 'text', value: '' }],
    text: '',
    occurrenceIds: [],
    attachmentIds: [],
  };
}

function cloneComposerValue(value: ComposerValue): ComposerValue {
  const occurrenceIds = [...(value.occurrenceIds || value.attachmentIds || [])];
  return {
    parts: value.parts.map((part) => ({ ...part })),
    text: value.text,
    occurrenceIds,
    attachmentIds: [...occurrenceIds],
  };
}

function appendComposerValues(current: ComposerValue, restored: ComposerValue): ComposerValue {
  if (!current.text && current.occurrenceIds.length === 0) return cloneComposerValue(restored);
  if (!restored.text && restored.occurrenceIds.length === 0) return cloneComposerValue(current);
  const separator: ComposerValue['parts'] = [{ type: 'text', value: '\n' }];
  const parts = [...current.parts, ...separator, ...restored.parts].map((part) => ({ ...part }));
  const occurrenceIds = parts.map(composerPartOccurrenceId).filter((id): id is string => !!id);
  return {
    parts,
    text: parts
      .filter((part) => part.type === 'text')
      .map((part) => part.value)
      .join(''),
    occurrenceIds,
    attachmentIds: [...occurrenceIds],
  };
}

// ── pill sub-components ──

function ModelPill({
  sessionModel,
  defaultModel,
  models,
  show,
  onApply,
}: {
  sessionModel: string;
  defaultModel: string;
  models: string[];
  show: boolean;
  onApply: (key: string, value: string) => void;
}) {
  if (!show) return null;

  const current = sessionModel || defaultModel;

  // 复用带搜索过滤的 ModelSelect（与 SettingsPopover 保持一致），仅通过
  // buttonClassName / menuClassName 适配 pill 外观与向上展开的交互。
  return (
    <div data-model-pill className="relative min-w-0 max-w-full shrink">
      <ModelSelect
        value={current}
        options={models}
        onChange={(m) => onApply('model', m)}
        buttonClassName={PILL_CLASS + ' min-w-0 max-w-full font-semibold'}
        menuClassName="absolute left-0 bottom-full mb-1 z-40 min-w-[160px] w-max"
      />
    </div>
  );
}

function PermissionPill({
  sessionMode,
  defaultMode,
  modes,
  show,
  onApply,
}: {
  sessionMode: string | null;
  defaultMode: string;
  modes: PermissionMode[];
  show: boolean;
  onApply: (key: string, value: string) => void;
}) {
  const [open, setOpen] = useState(false);
  const buttonRef = useRef<HTMLButtonElement>(null);
  const [menuPosition, setMenuPosition] = useState<{ left: number; bottom: number } | null>(null);
  const current = sessionMode || defaultMode;
  const active = modes.find((m) => m.value === current);
  // Keep the collapsed toolbar pill compact; the expanded menu still shows
  // the adapter's full label and its CLI hint.
  const label = (active?.label || current).replace(/\s*\(.*$/, '').trim();

  useEffect(() => {
    if (!open) return;
    const handler = (e: MouseEvent) => {
      const target = e.target as HTMLElement;
      if (!target.closest('[data-perm-pill]') && !target.closest('[data-permission-menu]'))
        setOpen(false);
    };
    document.addEventListener('mousedown', handler);
    return () => document.removeEventListener('mousedown', handler);
  }, [open]);

  useEffect(() => {
    if (!open) {
      setMenuPosition(null);
      return;
    }
    const update = () => {
      const rect = buttonRef.current?.getBoundingClientRect();
      if (rect) setMenuPosition({ left: rect.left, bottom: window.innerHeight - rect.top + 4 });
    };
    update();
    window.addEventListener('resize', update);
    window.addEventListener('scroll', update, true);
    return () => {
      window.removeEventListener('resize', update);
      window.removeEventListener('scroll', update, true);
    };
  }, [open]);

  if (!show) return null;

  return (
    <div data-perm-pill className="relative min-w-0 max-w-full shrink">
      <button
        ref={buttonRef}
        className={PILL_CLASS + ' ' + permBorderClass(current)}
        onClick={() => setOpen(!open)}
      >
        <span className="min-w-0 truncate">{label}</span>
        <ChevronDown size={12} />
      </button>
      {open &&
        menuPosition &&
        createPortal(
          <div
            data-permission-menu
            style={{ position: 'fixed', left: menuPosition.left, bottom: menuPosition.bottom }}
            className="z-[60] mb-1 min-w-[160px] rounded-md border border-border-default bg-bg-primary shadow-lg"
          >
            {modes.map((m) => (
              <div
                key={m.value}
                className={DROPDOWN_ITEM + (m.value === current ? ' bg-accent/10 text-accent' : '')}
                onClick={() => {
                  onApply('permissionMode', m.value);
                  setOpen(false);
                }}
              >
                {m.label}
              </div>
            ))}
          </div>,
          document.body,
        )}
    </div>
  );
}

function ThinkingToggle({
  enabled,
  show,
  onApply,
}: {
  enabled: boolean;
  show: boolean;
  onApply: (key: string, value: boolean) => void;
}) {
  if (!show) return null;

  return (
    <button
      className={PILL_CLASS + (enabled ? ' bg-accent/10 border-accent/50 text-accent' : '')}
      onClick={() => onApply('alwaysThinkingEnabled', !enabled)}
    >
      Thinking
    </button>
  );
}

// ── main component ──

export function InputRow() {
  const inputRef = useRef<HTMLTextAreaElement>(null);
  const composerRef = useRef<RichTextComposerHandle>(null);
  const composerValueRef = useRef<ComposerValue>({
    parts: [{ type: 'text', value: '' }],
    text: '',
    occurrenceIds: [],
    attachmentIds: [],
  });
  const settingsButtonRef = useRef<HTMLButtonElement>(null);
  const resizeStartRef = useRef<{ y: number; height: number } | null>(null);
  const currentSessionId = useSessionStore((s) => s.currentSessionId);
  const currentSession = useCurrentSession();
  const addMessage = useSessionStore((s) => s.addMessage);
  const setInputDraft = useSessionStore((s) => s.setInputDraft);
  const steer = useWorkerStore((s) => s.steer);
  // The worker store is keyed by durable sessionId and is refreshed from the
  // live worker registry independently of session summary refreshes.  Use that
  // runtime state for Steer visibility so a stale session snapshot cannot hide
  // a control that the session-level endpoint can still route successfully.
  const currentWorker = useWorkerStore((s) =>
    currentSessionId ? s.workers[currentSessionId] : null,
  );
  const { showToast } = useUIStore();
  const chatAttachmentRequests = useUIStore((s) => s.chatAttachmentRequests);
  const consumeChatAttachmentRequests = useUIStore((s) => s.consumeChatAttachmentRequests);
  const { isMobile } = useMediaQuery();
  const [settingsOpen, setSettingsOpen] = useState(false);
  const [composerHeight, setComposerHeight] = useState(180);
  const [resizing, setResizing] = useState(false);
  const [mobileFullscreen, setMobileFullscreen] = useState(false);
  const [attachmentMenuOpen, setAttachmentMenuOpen] = useState(false);
  const [attachmentBrowserOpen, setAttachmentBrowserOpen] = useState(false);
  const [attachmentBrowserPath, setAttachmentBrowserPath] = useState('');
  const [attachmentDirectoryError, setAttachmentDirectoryError] = useState<string | null>(null);
  const [attachments, setAttachments] = useState<PendingAttachment[]>([]);
  const [composerText, setComposerText] = useState(() =>
    currentSessionId ? useSessionStore.getState().inputDrafts[currentSessionId] || '' : '',
  );
  const clientAttachmentInputRef = useRef<HTMLInputElement>(null);
  const uploadControllersRef = useRef(new Map<string, AbortController>());
  const attachmentEpochRef = useRef(0);
  const activeAttachmentSessionRef = useRef<string | null>(currentSessionId);
  const sendSnapshotsRef = useRef(new Map<string, SendSnapshot>());
  const recoveryBySessionRef = useRef(new Map<string, SendSnapshot>());
  const pendingRecoveryValueRef = useRef<ComposerValue | null>(null);
  const enqueue = useQueueStore((s) => s.enqueue);
  const panelOpen = useQueueStore((s) => s.panelOpen);
  const togglePanel = useQueueStore((s) => s.togglePanel);
  // 队列计数（含编辑中的一条）：原始值比较，selector 稳定
  const queueCount = useQueueStore((s) => {
    if (!currentSessionId) return 0;
    const q = s.queues[currentSessionId];
    const e = s.edits[currentSessionId];
    return (q ? q.length : 0) + (e ? 1 : 0);
  });

  // ── Adapter settings ──
  const config = useAdapterStore((s) => s.getConfig());
  const loadConfig = useAdapterStore((s) => s.loadConfig);
  const applySettings = useAdapterStore((s) => s.applySettings);
  const { loadSessions } = useSessionStore();

  useEffect(() => {
    if (currentSession) {
      loadConfig(currentSession.adapter || 'cbc');
    }
  }, [currentSession, loadConfig]);

  const applySetting = async (key: string, value: unknown) => {
    if (!currentSession) return;
    try {
      await applySettings(currentSession.id, { [key]: value });
      await loadSessions();
    } catch (e) {
      showToast((e as Error).message || 'Failed', 'error');
    }
  };

  const closeAttachmentBrowser = () => {
    setAttachmentBrowserOpen(false);
    setAttachmentMenuOpen(false);
    setAttachmentDirectoryError(null);
  };

  // Restore draft when session changes. Reads from getState() so it does not
  // depend on `inputDrafts` (which would re-run — and reset the caret — on
  // every keystroke now that onChange persists drafts).
  useEffect(() => {
    const draft = currentSessionId ? useSessionStore.getState().inputDrafts[currentSessionId] : '';
    const recovery = currentSessionId
      ? recoveryBySessionRef.current.get(currentSessionId)
      : undefined;
    const value = recovery?.value || {
      parts: draft
        ? [{ type: 'text' as const, value: draft }]
        : [{ type: 'text' as const, value: '' }],
      text: draft || '',
      occurrenceIds: [],
      attachmentIds: [],
    };
    if (recovery) {
      pendingRecoveryValueRef.current = value;
      setAttachments(recovery.attachments.map((attachment) => ({ ...attachment })));
    } else {
      pendingRecoveryValueRef.current = null;
      setAttachments([]);
      composerRef.current?.replaceValue(value);
    }
    setComposerText(value.text);
  }, [currentSessionId]);

  useEffect(() => {
    const pending = pendingRecoveryValueRef.current;
    if (!pending) return;
    const occurrenceIds = new Set(attachments.map(attachmentOccurrenceId));
    const allAvailable = pending.occurrenceIds.every((occurrenceId) =>
      occurrenceIds.has(occurrenceId),
    );
    if (!allAvailable) return;
    pendingRecoveryValueRef.current = null;
    composerRef.current?.replaceValue(pending);
  }, [attachments, currentSessionId]);

  useEffect(() => {
    const uploadControllers = uploadControllersRef.current;
    attachmentEpochRef.current += 1;
    activeAttachmentSessionRef.current = currentSessionId;
    if (!currentSessionId) setAttachments([]);
    setAttachmentBrowserOpen(false);
    setAttachmentMenuOpen(false);
    return () => {
      for (const controller of uploadControllers.values()) controller.abort();
      uploadControllers.clear();
      attachmentEpochRef.current += 1;
    };
  }, [currentSessionId]);

  // The editor can be a separate route, so it hands a server path to the
  // mounted composer through a one-shot UI request. The actual attachment
  // state, formatting, and queue submission remain owned by InputRow.
  useEffect(() => {
    if (!currentSessionId) return;
    const requested = chatAttachmentRequests
      .filter((request) => request.sessionId === currentSessionId)
      .map((request) => request.path);
    if (requested.length === 0) return;
    const register = isMockMode() ? mockRegisterServerFileAttachment : registerServerFileAttachment;
    const sessionEpoch = attachmentEpochRef.current;
    void Promise.all(requested.map((path) => register(currentSessionId, path)))
      .then((registered) => {
        if (
          activeAttachmentSessionRef.current !== currentSessionId ||
          attachmentEpochRef.current !== sessionEpoch
        )
          return;
        setAttachments((current) => {
          const additions = registered.map((item) => {
            const occurrenceId = attachmentId();
            return {
              occurrenceId,
              id: occurrenceId,
              attachmentId: item.attachmentId,
              displayName: item.displayName,
              path: item.path,
              href: item.href,
              mimeType: item.mimeType,
              source: 'server_file' as const,
              status: 'ready' as const,
            };
          });
          return additions.length > 0 ? [...current, ...additions] : current;
        });
      })
      .catch((error) => {
        if (
          activeAttachmentSessionRef.current !== currentSessionId ||
          attachmentEpochRef.current !== sessionEpoch
        )
          return;
        showToast(error instanceof Error ? error.message : '服务端附件注册失败', 'error');
      });
    consumeChatAttachmentRequests(currentSessionId, requested);
  }, [chatAttachmentRequests, consumeChatAttachmentRequests, currentSessionId, showToast]);

  useEffect(() => {
    if (!isMobile) {
      setMobileFullscreen(false);
      setResizing(false);
      resizeStartRef.current = null;
    }
  }, [isMobile]);

  useEffect(() => {
    if (isMobile) return;
    const handlePointerMove = (event: PointerEvent) => {
      const start = resizeStartRef.current;
      if (!start) return;
      setComposerHeight(Math.min(520, Math.max(120, start.height + start.y - event.clientY)));
    };
    const stopResizing = () => {
      resizeStartRef.current = null;
      setResizing(false);
    };
    document.addEventListener('pointermove', handlePointerMove);
    document.addEventListener('pointerup', stopResizing);
    document.addEventListener('pointercancel', stopResizing);
    return () => {
      document.removeEventListener('pointermove', handlePointerMove);
      document.removeEventListener('pointerup', stopResizing);
      document.removeEventListener('pointercancel', stopResizing);
    };
  }, [isMobile]);

  useEffect(() => {
    if (!isMobile || !mobileFullscreen) return;
    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'Escape') setMobileFullscreen(false);
    };
    document.addEventListener('keydown', handleKeyDown);
    return () => document.removeEventListener('keydown', handleKeyDown);
  }, [isMobile, mobileFullscreen]);

  const handleResizePointerDown = (event: React.PointerEvent<HTMLDivElement>) => {
    if (isMobile) return;
    event.preventDefault();
    resizeStartRef.current = { y: event.clientY, height: composerHeight };
    setResizing(true);
    event.currentTarget.setPointerCapture?.(event.pointerId);
  };

  const handleResizePointerMove = (event: React.PointerEvent<HTMLDivElement>) => {
    if (isMobile) return;
    const start = resizeStartRef.current;
    if (!start) return;
    setComposerHeight(Math.min(520, Math.max(120, start.height + start.y - event.clientY)));
  };

  const uploadClientAttachment = useCallback(
    async (attachment: PendingAttachment) => {
      const sessionId = currentSessionId;
      if (!sessionId || !attachment.file) return;
      const sessionEpoch = attachmentEpochRef.current;
      const controller = new AbortController();
      uploadControllersRef.current.set(attachmentOccurrenceId(attachment), controller);
      const isLive = () =>
        activeAttachmentSessionRef.current === sessionId &&
        attachmentEpochRef.current === sessionEpoch &&
        uploadControllersRef.current.get(attachmentOccurrenceId(attachment)) === controller;
      try {
        const upload = isMockMode() ? mockUploadSessionAttachment : uploadSessionAttachment;
        const uploaded = await upload(
          sessionId,
          attachment.file,
          (loaded, total) => {
            if (!isLive()) return;
            setAttachments((current) =>
              current.map((item) =>
                attachmentOccurrenceId(item) === attachmentOccurrenceId(attachment)
                  ? { ...item, loadedBytes: loaded, totalBytes: total }
                  : item,
              ),
            );
          },
          controller.signal,
        );
        if (!isLive()) return;
        setAttachments((current) =>
          current.map((item) =>
            attachmentOccurrenceId(item) === attachmentOccurrenceId(attachment)
              ? {
                  ...item,
                  displayName: uploaded.displayName || uploaded.filename || item.displayName,
                  path: uploaded.path,
                  href: uploaded.href || serverFileDownloadHref(sessionId, uploaded.path),
                  status: 'ready',
                  attachmentId: uploaded.attachmentId || uploaded.storageFilename,
                  mimeType: attachment.file?.type || undefined,
                  source: 'upload',
                  loadedBytes: uploaded.size,
                  totalBytes: uploaded.size,
                  error: undefined,
                }
              : item,
          ),
        );
      } catch (error) {
        if (!isLive()) return;
        setAttachments((current) =>
          current.map((item) =>
            attachmentOccurrenceId(item) === attachmentOccurrenceId(attachment)
              ? {
                  ...item,
                  status: 'error',
                  error: error instanceof Error ? error.message : String(error),
                }
              : item,
          ),
        );
      } finally {
        if (uploadControllersRef.current.get(attachmentOccurrenceId(attachment)) === controller) {
          uploadControllersRef.current.delete(attachmentOccurrenceId(attachment));
        }
      }
    },
    [currentSessionId],
  );

  const queueClientFiles = useCallback(
    (files: File[]): string[] => {
      if (!currentSessionId || files.length === 0) return [];
      const uploadingOrReady = new Set(
        attachments
          .filter((attachment) => attachment.status !== 'error' && attachment.fileKey)
          .map((attachment) => attachment.fileKey),
      );
      const selectedKeys = new Set(uploadingOrReady);
      const added = files
        .filter((file) => {
          const key = clientFileKey(file);
          if (selectedKeys.has(key)) return false;
          selectedKeys.add(key);
          return true;
        })
        .map((file) => ({
          occurrenceId: attachmentId(),
          id: '',
          displayName: file.name,
          file,
          fileKey: clientFileKey(file),
          loadedBytes: 0,
          totalBytes: file.size,
          status: 'uploading' as const,
        }))
        .map((attachment) => ({ ...attachment, id: attachment.occurrenceId }));
      if (added.length === 0) return [];
      setAttachments((current) => [...current, ...added]);
      void Promise.all(added.map((attachment) => uploadClientAttachment(attachment)));
      return added.map((attachment) => attachment.id);
    },
    [attachments, currentSessionId, uploadClientAttachment],
  );

  const handleClientFiles = useCallback(
    (event: React.ChangeEvent<HTMLInputElement>) => {
      const files = Array.from(event.target.files || []);
      event.target.value = '';
      void queueClientFiles(files);
    },
    [queueClientFiles],
  );

  const handleNativeFiles = useCallback(
    (files: File[], _offset: number, _source: 'paste' | 'drop') => queueClientFiles(files),
    [queueClientFiles],
  );

  const handleNativeInputIssue = useCallback(
    (kind: 'directory' | 'uri' | 'invalid-pan-attachment') => {
      if (kind === 'directory') showToast('暂不支持拖入目录；请先选择普通文件', 'error');
      else if (kind === 'uri') showToast('不接受文件 URI/路径，请拖入普通文件内容', 'error');
      else showToast('Pan 附件引用无效，请重新拖入附件', 'error');
    },
    [showToast],
  );

  const handleComposerChange = useCallback(
    (value: ComposerValue) => {
      composerValueRef.current = value;
      setComposerText(value.text);
      if (currentSessionId) {
        const recovery = recoveryBySessionRef.current.get(currentSessionId);
        if (
          recovery &&
          (recovery.value.text !== value.text ||
            recovery.value.occurrenceIds.join('\u0000') !== value.occurrenceIds.join('\u0000'))
        ) {
          recoveryBySessionRef.current.delete(currentSessionId);
        }
        setInputDraft(currentSessionId, value.text);
      }
    },
    [currentSessionId, setInputDraft],
  );

  const handleAttachmentDrop = useCallback(
    (payload: PanAttachmentPayload): string | null => {
      if (!currentSessionId) return null;
      if (!isAttachmentPayloadForSession(payload, currentSessionId)) {
        showToast('附件属于其他 Session，不能拖入当前输入框', 'error');
        return null;
      }
      if (
        payload.attachmentId &&
        (payload.source === 'composer' || payload.source === 'attachment-chip')
      ) {
        const existing = attachments.find(
          (attachment) => attachmentOccurrenceId(attachment) === payload.attachmentId,
        );
        if (existing) return attachmentOccurrenceId(existing);
      }
      const occurrenceId = attachmentId();
      const remoteId = payload.serverAttachmentId || uploadAttachmentIdFromHref(payload.href);
      const needsRegistration = !remoteId && !!payload.path;
      setAttachments((current) => [
        ...current,
        {
          occurrenceId,
          id: occurrenceId,
          attachmentId: remoteId,
          displayName: payload.displayName,
          path: payload.path,
          href: payload.href,
          location: payload.location,
          status: needsRegistration ? 'registering' : 'ready',
          source: remoteId?.startsWith('upload_') ? 'upload' : 'server_file',
        },
      ]);
      if (needsRegistration) {
        const register = isMockMode()
          ? mockRegisterServerFileAttachment
          : registerServerFileAttachment;
        const sessionEpoch = attachmentEpochRef.current;
        void register(currentSessionId, payload.path!)
          .then((registered) => {
            if (
              activeAttachmentSessionRef.current !== currentSessionId ||
              attachmentEpochRef.current !== sessionEpoch
            )
              return;
            setAttachments((current) =>
              current.map((item) =>
                attachmentOccurrenceId(item) === occurrenceId
                  ? {
                      ...item,
                      attachmentId: registered.attachmentId,
                      displayName: registered.displayName,
                      href: registered.href,
                      path: registered.path,
                      mimeType: registered.mimeType,
                      source: 'server_file',
                      status: 'ready',
                    }
                  : item,
              ),
            );
          })
          .catch((error) => {
            if (
              activeAttachmentSessionRef.current !== currentSessionId ||
              attachmentEpochRef.current !== sessionEpoch
            )
              return;
            setAttachments((current) =>
              current.map((item) =>
                attachmentOccurrenceId(item) === occurrenceId
                  ? {
                      ...item,
                      status: 'error',
                      error: error instanceof Error ? error.message : '附件注册失败',
                    }
                  : item,
              ),
            );
          });
      }
      return occurrenceId;
    },
    [attachments, currentSessionId, showToast],
  );

  const handleRemoveComposerAttachment = useCallback((attachmentIdToRemove: string) => {
    uploadControllersRef.current.get(attachmentIdToRemove)?.abort();
    uploadControllersRef.current.delete(attachmentIdToRemove);
    setAttachments((current) =>
      current.filter((attachment) => attachmentOccurrenceId(attachment) !== attachmentIdToRemove),
    );
  }, []);

  const restoreSubmission = useCallback(
    (snapshot: SendSnapshot) => {
      const activeSessionId = useSessionStore.getState().currentSessionId;
      const oldDraft = useSessionStore.getState().inputDrafts[snapshot.sessionId] || '';
      if (activeSessionId !== snapshot.sessionId) {
        const existing = oldDraft
          ? {
              parts: [{ type: 'text' as const, value: oldDraft }],
              text: oldDraft,
              occurrenceIds: [],
              attachmentIds: [],
            }
          : emptyComposerValue();
        const value = appendComposerValues(existing, snapshot.value);
        useSessionStore.getState().setInputDraft(snapshot.sessionId, value.text);
        // Keep the attachment-bearing recovery alongside the Session draft.
        // The old Session may already have a newer text draft when this
        // request settles, so restoring only the plain draft would lose
        // attachment occurrences.
        recoveryBySessionRef.current.set(snapshot.sessionId, { ...snapshot, value });
        return;
      }

      const current = composerValueRef.current;
      const hasCurrentInput = !!current.text || current.occurrenceIds.length > 0;
      const value = hasCurrentInput
        ? appendComposerValues(current, snapshot.value)
        : cloneComposerValue(snapshot.value);
      setAttachments((currentAttachments) => {
        const existingIds = new Set(currentAttachments.map(attachmentOccurrenceId));
        const additions = snapshot.attachments
          .filter((attachment) => !existingIds.has(attachmentOccurrenceId(attachment)))
          .map((attachment) => ({ ...attachment }));
        return additions.length ? [...currentAttachments, ...additions] : currentAttachments;
      });
      pendingRecoveryValueRef.current = value;
      if (
        !value.occurrenceIds.length ||
        value.occurrenceIds.every((occurrenceId) =>
          attachments.some((attachment) => attachmentOccurrenceId(attachment) === occurrenceId),
        )
      ) {
        pendingRecoveryValueRef.current = null;
        composerRef.current?.replaceValue(value);
      }
      setInputDraft(snapshot.sessionId, value.text);
      // Keep a retryable snapshot even when new input was merged into the
      // failed submission.  A later Session switch or remount must restore
      // both the merged text and every attachment occurrence.
      recoveryBySessionRef.current.set(snapshot.sessionId, { ...snapshot, value });
    },
    [attachments, setInputDraft],
  );

  const handleSend = useCallback(
    (_text: string) => {
      if (!currentSessionId) {
        showToast('Select a session first');
        return;
      }
      if (attachments.some((attachment) => attachment.status === 'uploading')) {
        showToast('附件仍在上传，请稍候', 'error');
        return;
      }
      if (attachments.some((attachment) => attachment.status === 'registering')) {
        showToast('附件仍在注册，请稍候', 'error');
        return;
      }
      if (attachments.some((attachment) => attachment.status === 'error')) {
        showToast('有附件上传失败，请重试或取消', 'error');
        return;
      }
      const value = cloneComposerValue(composerValueRef.current);
      const snapshotAttachments = attachments.map((attachment) => ({ ...attachment }));
      const readyAttachments = snapshotAttachments.filter(
        (attachment): attachment is PendingAttachment & { href: string } =>
          attachment.status === 'ready' && !!attachment.href,
      );
      const attachmentLinks = readyAttachments.map((attachment) =>
        attachmentMarkdown({
          displayName: attachment.displayName,
          href: attachment.href,
          location: attachment.location,
        }),
      );
      if (
        attachmentLinks.some((link) => link === null) ||
        attachmentLinks.length !== snapshotAttachments.length
      ) {
        showToast('附件链接无效，请重新选择附件', 'error');
        return;
      }
      if (readyAttachments.some((attachment) => !attachment.attachmentId)) {
        showToast('附件身份尚未完成，请重新选择或等待附件注册', 'error');
        return;
      }
      const linksById = new Map(
        readyAttachments.map((attachment, index) => [
          attachmentOccurrenceId(attachment),
          attachmentLinks[index],
        ]),
      );
      const embeddedIds = new Set(value.occurrenceIds);
      const composedText = value.parts
        .map((part) => {
          if (part.type === 'text') return part.value;
          return linksById.get(composerPartOccurrenceId(part) || '') || '';
        })
        .join('');
      const remainingLinks = readyAttachments
        .filter((attachment) => !embeddedIds.has(attachmentOccurrenceId(attachment)))
        .map((attachment) => linksById.get(attachmentOccurrenceId(attachment)))
        .filter((link): link is string => !!link);
      const message = [composedText, remainingLinks.join(' ')]
        .filter((part) => part.trim())
        .join(' ');
      if (!message) return;
      if (
        [...sendSnapshotsRef.current.values()].some(
          (pending) =>
            pending.sessionId === currentSessionId &&
            pending.message === message &&
            pending.value.text === value.text &&
            pending.value.occurrenceIds.join('\u0000') === value.occurrenceIds.join('\u0000'),
        )
      )
        return;

      const structuredParts: MessagePart[] = [];
      for (const part of value.parts) {
        if (part.type === 'text') {
          structuredParts.push({ type: 'text', text: part.value });
          continue;
        }
        const attachment = snapshotAttachments.find(
          (candidate) => attachmentOccurrenceId(candidate) === composerPartOccurrenceId(part),
        );
        if (attachment?.attachmentId) {
          structuredParts.push({
            type: 'attachment',
            attachmentId: attachment.attachmentId,
            displayName: attachment.displayName,
            mimeType: attachment.mimeType,
            size: attachment.file?.size,
            source: attachment.source,
            ...(attachment.location ? { location: attachment.location } : {}),
          });
        }
      }
      for (const attachment of readyAttachments) {
        if (embeddedIds.has(attachmentOccurrenceId(attachment))) continue;
        if (structuredParts.length > 0) structuredParts.push({ type: 'text', text: ' ' });
        structuredParts.push({
          type: 'attachment',
          attachmentId: attachment.attachmentId!,
          displayName: attachment.displayName,
          mimeType: attachment.mimeType,
          size: attachment.file?.size,
          source: attachment.source,
          ...(attachment.location ? { location: attachment.location } : {}),
        });
      }

      const recovery = recoveryBySessionRef.current.get(currentSessionId);
      const canReuseClientMessageId =
        !!recovery &&
        recovery.value.text === value.text &&
        recovery.value.occurrenceIds.join('\u0000') === value.occurrenceIds.join('\u0000') &&
        recovery.attachments.map(attachmentOccurrenceId).join('\u0000') ===
          snapshotAttachments.map(attachmentOccurrenceId).join('\u0000');
      const snapshot: SendSnapshot = {
        transactionId: attachmentId(),
        clientMessageId: canReuseClientMessageId ? recovery!.clientMessageId : attachmentId(),
        sessionId: currentSessionId,
        value,
        attachments: snapshotAttachments,
        message,
        parts: structuredParts.length > 0 ? structuredParts : undefined,
      };
      sendSnapshotsRef.current.set(snapshot.transactionId, snapshot);

      // The user transaction is cleared synchronously.  All later async
      // work is tied to this snapshot and session, so new typing can never be
      // cleared or restored by the old request.
      composerRef.current?.replaceValue(emptyComposerValue());
      setInputDraft(currentSessionId, '');
      setAttachments((current) =>
        current.filter(
          (attachment) =>
            !snapshotAttachments.some(
              (sent) => attachmentOccurrenceId(sent) === attachmentOccurrenceId(attachment),
            ),
        ),
      );

      void (async () => {
        try {
          const serverAttachments = snapshot.attachments.filter(
            (attachment) => !attachment.file && attachment.status === 'ready' && !!attachment.path,
          );
          const valid = await Promise.all(
            serverAttachments.map((attachment) =>
              directoryEntryExists(attachment.path!, fetchDirectories),
            ),
          );
          if (valid.some((exists) => !exists)) {
            if (useSessionStore.getState().currentSessionId === snapshot.sessionId) {
              setAttachmentDirectoryError('当前目录非法');
              const stalePath = serverAttachments[0]?.path;
              if (stalePath) setAttachmentBrowserPath(parentDirectory(stalePath));
              setAttachmentBrowserOpen(true);
              setAttachmentMenuOpen(false);
              showToast('当前目录非法', 'error');
            }
            throw new Error('当前目录非法');
          }
          const ok = await enqueue(
            snapshot.message,
            snapshot.parts,
            snapshot.sessionId,
            snapshot.clientMessageId,
          );
          if (!ok) throw new Error('消息尚未入队');
          sendSnapshotsRef.current.delete(snapshot.transactionId);
          recoveryBySessionRef.current.delete(snapshot.sessionId);
        } catch {
          if (sendSnapshotsRef.current.get(snapshot.transactionId) !== snapshot) return;
          sendSnapshotsRef.current.delete(snapshot.transactionId);
          restoreSubmission(snapshot);
        }
      })();
    },
    [
      currentSessionId,
      showToast,
      setInputDraft,
      enqueue,
      attachments,
      restoreSubmission,
      setAttachmentDirectoryError,
      setAttachmentBrowserPath,
      setAttachmentBrowserOpen,
      setAttachmentMenuOpen,
    ],
  );

  const handleSteer = useCallback(
    async (text: string) => {
      if (!currentSessionId || !text.trim()) return;
      try {
        await steer(currentSessionId, text);
        composerRef.current?.replaceText('');
        setInputDraft(currentSessionId, '');
        // Optimistic append; the server stamps the same moment into history
        // (steer_worker appends + saves right after the control write).
        addMessage({ role: 'user', content: text, ts: new Date().toISOString() });
      } catch (e) {
        showToast((e as Error).message || 'Steer failed', 'error');
      }
    },
    [currentSessionId, steer, setInputDraft, addMessage, showToast],
  );

  const handleKeyDown = (e: React.KeyboardEvent<HTMLElement>) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSend(composerValueRef.current.text);
    }
  };

  const showModelPill = supportsSetting(config, 'model');
  const showPermPill = supportsSetting(config, 'permissionMode');
  const showThinking = supportsSetting(config, 'thinking');
  // Effort only makes sense with thinking enabled (mirrors SettingsPopover).
  const showEffort =
    supportsSetting(config, 'effort') && (!showThinking || !!currentSession?.alwaysThinkingEnabled);
  const modelEfforts = config?.modelEfforts?.[currentSession?.model || config?.defaultModel || ''];
  const effortValues = modelEfforts ? ['', ...modelEfforts] : config?.effortValues || [];
  // opencode's effort list starts with "" (unset sentinel); filter it out so
  // the dropdown never renders a blank <option>, and surface it as a clear
  // "默认" placeholder instead.
  const validEffortValues = effortValues.filter((v) => v && String(v).trim() !== '');
  const hadEmptyEffort = effortValues.length !== validEffortValues.length;
  const currentEffort =
    currentSession?.effort && validEffortValues.includes(currentSession.effort.trim())
      ? currentSession.effort
      : hadEmptyEffort
        ? ''
        : (validEffortValues[0] ?? '');
  const canSteer =
    currentSession?.adapter === 'codex' &&
    currentWorker?.status === 'running' &&
    !!currentWorker.id;
  const clientAttachments = attachments.filter((attachment) => !!attachment.file);
  const uploadTotalBytes = clientAttachments.reduce(
    (total, attachment) => total + (attachment.totalBytes ?? attachment.file?.size ?? 0),
    0,
  );
  const uploadLoadedBytes = clientAttachments.reduce(
    (loaded, attachment) =>
      loaded +
      (attachment.status === 'ready'
        ? (attachment.totalBytes ?? attachment.file?.size ?? 0)
        : (attachment.loadedBytes ?? 0)),
    0,
  );
  const uploadPercent =
    uploadTotalBytes > 0
      ? Math.min(100, Math.floor((uploadLoadedBytes / uploadTotalBytes) * 100))
      : clientAttachments.every((attachment) => attachment.status === 'ready')
        ? 100
        : 0;
  const uploadStatus = clientAttachments.some((attachment) => attachment.status === 'uploading')
    ? '上传中'
    : clientAttachments.some((attachment) => attachment.status === 'error')
      ? '失败'
      : '已完成';
  const attachmentsBlocked = attachments.some((attachment) => attachment.status !== 'ready');
  const embeddedAttachmentIds = new Set(composerValueRef.current.occurrenceIds);
  const visibleAttachmentChips = attachments.filter(
    (attachment) => !embeddedAttachmentIds.has(attachmentOccurrenceId(attachment)),
  );

  return (
    <div
      data-testid="input-row"
      className={`relative flex shrink-0 w-full flex-col border-t border-border-default bg-bg-primary ${
        isMobile && mobileFullscreen
          ? 'fixed inset-0 z-50 h-[100dvh] overflow-hidden pt-[var(--safe-top)]'
          : ''
      }`}
      style={!isMobile ? { height: `${composerHeight}px` } : undefined}
    >
      {!isMobile && (
        <div
          data-testid="desktop-composer-resize"
          role="separator"
          aria-label="调整输入区高度"
          aria-orientation="horizontal"
          onPointerDown={handleResizePointerDown}
          onPointerMove={handleResizePointerMove}
          className={`h-1 w-full shrink-0 cursor-ns-resize touch-none hover:bg-accent/50 ${resizing ? 'bg-accent/50' : ''}`}
        />
      )}
      {/* 待发送队列面板（默认折叠，^ 按钮展开） */}
      <div
        data-testid="send-queue-anchor"
        className={
          isMobile && mobileFullscreen ? 'shrink-0' : 'absolute inset-x-0 bottom-full z-20'
        }
      >
        <SendQueuePanel />
      </div>

      {/* 左列：settings gear（有会话时）+ 队列开关 ^ 上下垂直紧凑堆叠，节省一行。
          右侧内容列：pill 行 + textarea/Send 行。 */}
      <div className="flex min-h-0 flex-1 gap-2 px-3 pt-2 pb-[max(16px,var(--safe-bottom))] md:pb-3">
        {/* 右侧内容列 */}
        <div className={`flex-1 min-w-0 flex flex-col gap-2 ${mobileFullscreen ? 'min-h-0' : ''}`}>
          {currentSession && (
            <div
              data-testid="input-control-row"
              className="flex min-w-0 max-w-full flex-nowrap items-center gap-1 overflow-visible"
            >
              <div className="flex shrink-0 items-center gap-1">
                <div data-settings-popover className="relative">
                  <button
                    ref={settingsButtonRef}
                    onClick={() => setSettingsOpen((v) => !v)}
                    title="Session settings"
                    aria-label="Session settings"
                    className={`flex h-7 w-7 items-center justify-center rounded border transition-colors ${settingsOpen ? 'border-accent/50 bg-accent/10 text-accent' : 'border-border-default bg-bg-tertiary text-text-secondary hover:bg-bg-hover hover:text-text-primary'}`}
                  >
                    <Settings size={14} />
                  </button>
                  <SettingsPopover
                    anchorRef={settingsButtonRef}
                    open={settingsOpen}
                    onClose={() => setSettingsOpen(false)}
                  />
                </div>
                <div className="relative">
                  <button
                    onClick={togglePanel}
                    title={queueCount > 0 ? `发送队列（${queueCount} 条待发）` : '发送队列'}
                    aria-label="发送队列"
                    className={`flex h-7 w-7 shrink-0 items-center justify-center rounded border transition-colors md:h-8 md:w-auto md:px-2 ${panelOpen || queueCount > 0 ? 'border-accent/50 bg-accent/10 text-accent' : 'border-border-default bg-bg-tertiary text-text-secondary hover:bg-bg-hover'}`}
                  >
                    <ChevronUp
                      size={14}
                      className={`transition-transform duration-200 ${panelOpen ? 'rotate-180' : ''}`}
                    />
                    <span className="ml-1 hidden text-xs md:inline">Queue</span>
                  </button>
                  {queueCount > 0 && (
                    <span className="absolute -top-1.5 -right-1.5 flex h-4 min-w-4 items-center justify-center rounded-full bg-accent px-1 text-[10px] font-medium leading-none text-white">
                      {queueCount > 99 ? '99+' : queueCount}
                    </span>
                  )}
                </div>
              </div>
              <ModelPill
                sessionModel={currentSession.model || ''}
                defaultModel={config?.defaultModel || ''}
                models={config?.models || []}
                show={showModelPill}
                onApply={applySetting}
              />
              <div className="hidden md:flex">
                <PermissionPill
                  sessionMode={currentSession.permissionMode || null}
                  defaultMode={config?.defaultPermissionMode || ''}
                  modes={config?.permissionModes || []}
                  show={showPermPill}
                  onApply={applySetting}
                />
              </div>
              <div className="hidden md:flex shrink-0">
                <ThinkingToggle
                  enabled={currentSession.alwaysThinkingEnabled}
                  show={showThinking}
                  onApply={applySetting}
                />
              </div>
              {showEffort && validEffortValues.length > 0 && (
                <select
                  value={currentEffort}
                  onChange={(e) => applySetting('effort', e.target.value)}
                  className="rounded-md border border-border-default bg-bg-tertiary px-1 py-1 text-xs text-text-primary focus:outline-none focus:border-accent"
                  title="Effort"
                >
                  {hadEmptyEffort && <option value="">默认</option>}
                  {validEffortValues.map((v) => (
                    <option key={v} value={v}>
                      {v}
                    </option>
                  ))}
                </select>
              )}
              <div className="relative order-last shrink-0 md:ml-auto">
                <button
                  type="button"
                  aria-label="添加附件"
                  title="添加附件"
                  onClick={() => setAttachmentMenuOpen((open) => !open)}
                  className={`flex h-7 w-7 items-center justify-center rounded border transition-colors ${attachmentMenuOpen ? 'border-accent/50 bg-accent/10 text-accent' : 'border-border-default bg-bg-tertiary text-text-secondary hover:bg-bg-hover'}`}
                >
                  <Paperclip size={14} />
                </button>
                {attachmentMenuOpen &&
                  createPortal(
                    <div
                      data-testid="attachment-menu"
                      className="fixed bottom-20 right-3 z-[60] min-w-[150px] rounded-md border border-border-default bg-bg-primary py-1 shadow-lg"
                    >
                      <button
                        type="button"
                        className="flex w-full items-center gap-2 px-3 py-2 text-left text-xs text-text-primary hover:bg-bg-hover"
                        onClick={() => {
                          setAttachmentBrowserPath('');
                          setAttachmentBrowserOpen(true);
                        }}
                      >
                        <FileIcon size={14} /> 服务端附件
                      </button>
                      <button
                        type="button"
                        className="flex w-full items-center gap-2 px-3 py-2 text-left text-xs text-text-primary hover:bg-bg-hover"
                        onClick={() => {
                          clientAttachmentInputRef.current?.click();
                          setAttachmentMenuOpen(false);
                        }}
                      >
                        <Paperclip size={14} /> 客户端附件
                      </button>
                    </div>,
                    document.body,
                  )}
              </div>
              {isMobile && (
                <button
                  type="button"
                  data-testid="mobile-input-fullscreen"
                  aria-label={mobileFullscreen ? '退出全屏输入' : '全屏输入'}
                  title={mobileFullscreen ? '退出全屏输入' : '全屏输入'}
                  onClick={() => setMobileFullscreen((current) => !current)}
                  className="flex h-7 w-7 shrink-0 items-center justify-center rounded border border-border-default bg-bg-tertiary text-text-secondary hover:bg-bg-hover"
                >
                  {mobileFullscreen ? <Minimize2 size={14} /> : <Expand size={14} />}
                </button>
              )}
            </div>
          )}

          {/* Textarea + Send row */}
          {clientAttachments.length > 0 && (
            <div className="flex flex-col gap-1.5" data-testid="attachment-upload-progress">
              <div className="flex items-center justify-between text-xs text-text-secondary">
                <span>客户端附件：{uploadStatus}</span>
                <span>{uploadPercent}%</span>
              </div>
              <div
                className="h-1.5 w-full overflow-hidden rounded-full bg-bg-tertiary"
                role="progressbar"
                aria-label="客户端附件上传进度"
                aria-valuemin={0}
                aria-valuemax={100}
                aria-valuenow={uploadPercent}
              >
                <div
                  className={`h-full transition-[width] ${uploadStatus === '失败' ? 'bg-danger' : 'bg-accent'}`}
                  style={{ width: `${uploadPercent}%` }}
                />
              </div>
            </div>
          )}
          {visibleAttachmentChips.length > 0 && (
            <div className="flex flex-wrap gap-1.5" data-testid="server-attachments">
              {visibleAttachmentChips.map((attachment) => (
                <span
                  key={attachmentOccurrenceId(attachment)}
                  draggable={attachment.status === 'ready' && !!attachment.href}
                  data-testid={
                    attachment.status === 'ready' && attachment.href
                      ? 'draggable-attachment-chip'
                      : undefined
                  }
                  onDragStart={(event) => {
                    if (attachment.status !== 'ready' || !attachment.href) return;
                    writePanAttachmentPayload(event.dataTransfer, {
                      displayName: attachment.displayName,
                      href: attachment.href,
                      path: attachment.path,
                      attachmentId: attachmentOccurrenceId(attachment),
                      serverAttachmentId: attachment.attachmentId,
                      source: 'attachment-chip',
                      sourceSessionId: currentSessionId || undefined,
                      location: attachment.location,
                    });
                  }}
                  role="group"
                  aria-label={`附件 ${attachment.displayName}`}
                  className="inline-flex max-w-full items-center gap-1 rounded border border-border-default bg-bg-tertiary px-2 py-1 text-xs text-text-secondary"
                  title={attachment.path || attachment.displayName}
                >
                  <FileIcon size={13} className="shrink-0" aria-hidden="true" />
                  <span className="truncate">{attachment.displayName}</span>
                  {attachment.file && attachment.status === 'uploading' && (
                    <span className="text-text-tertiary">上传中…</span>
                  )}
                  {!attachment.file && attachment.status === 'registering' && (
                    <span className="text-text-tertiary">注册中…</span>
                  )}
                  {attachment.file && attachment.status === 'ready' && (
                    <span className="text-accent">已完成</span>
                  )}
                  {attachment.status === 'error' && (
                    <button
                      type="button"
                      className="text-danger hover:underline"
                      aria-label={`重试上传 ${attachment.displayName}`}
                      onClick={() => {
                        if (attachment.file) {
                          setAttachments((current) =>
                            current.map((item) =>
                              attachmentOccurrenceId(item) === attachmentOccurrenceId(attachment)
                                ? { ...item, status: 'uploading', error: undefined }
                                : item,
                            ),
                          );
                          void uploadClientAttachment({ ...attachment, status: 'uploading' });
                          return;
                        }
                        if (attachment.path) {
                          const retrySessionId = currentSessionId;
                          const retryEpoch = attachmentEpochRef.current;
                          if (!retrySessionId) return;
                          setAttachments((current) =>
                            current.map((item) =>
                              attachmentOccurrenceId(item) === attachmentOccurrenceId(attachment)
                                ? { ...item, status: 'registering', error: undefined }
                                : item,
                            ),
                          );
                          const register = isMockMode()
                            ? mockRegisterServerFileAttachment
                            : registerServerFileAttachment;
                          void register(retrySessionId, attachment.path)
                            .then((registered) => {
                              if (
                                activeAttachmentSessionRef.current !== retrySessionId ||
                                attachmentEpochRef.current !== retryEpoch
                              )
                                return;
                              setAttachments((current) =>
                                current.map((item) =>
                                  attachmentOccurrenceId(item) ===
                                  attachmentOccurrenceId(attachment)
                                    ? {
                                        ...item,
                                        attachmentId: registered.attachmentId,
                                        href: registered.href,
                                        displayName: registered.displayName,
                                        mimeType: registered.mimeType,
                                        status: 'ready',
                                      }
                                    : item,
                                ),
                              );
                            })
                            .catch((error) => {
                              if (
                                activeAttachmentSessionRef.current !== retrySessionId ||
                                attachmentEpochRef.current !== retryEpoch
                              )
                                return;
                              setAttachments((current) =>
                                current.map((item) =>
                                  attachmentOccurrenceId(item) ===
                                  attachmentOccurrenceId(attachment)
                                    ? {
                                        ...item,
                                        status: 'error',
                                        error:
                                          error instanceof Error ? error.message : '附件注册失败',
                                      }
                                    : item,
                                ),
                              );
                            });
                        }
                      }}
                    >
                      重试
                    </button>
                  )}
                  {attachment.error && (
                    <span className="max-w-[180px] truncate text-danger" title={attachment.error}>
                      ({attachment.error})
                    </span>
                  )}
                  <button
                    type="button"
                    aria-label={`取消附件 ${attachment.displayName}`}
                    className="ml-1 text-danger hover:text-danger/80"
                    onClick={() => {
                      uploadControllersRef.current.get(attachmentOccurrenceId(attachment))?.abort();
                      uploadControllersRef.current.delete(attachmentOccurrenceId(attachment));
                      setAttachments((current) =>
                        current.filter(
                          (item) =>
                            attachmentOccurrenceId(item) !== attachmentOccurrenceId(attachment),
                        ),
                      );
                    }}
                  >
                    <X size={13} />
                  </button>
                </span>
              ))}
            </div>
          )}
          <Modal
            open={attachmentBrowserOpen}
            onClose={closeAttachmentBrowser}
            title="选择服务端附件"
            size="xl"
            mobileFullscreen={isMobile}
            className="md:max-h-[90vh]"
          >
            <div aria-label="Server attachment browser">
              <DirectoryInput
                value={attachmentBrowserPath}
                onChange={(path) => {
                  setAttachmentDirectoryError(null);
                  setAttachmentBrowserPath(path);
                }}
                fileMode
                showRootsWhenEmpty
                onSelect={(selectedPath) => {
                  const selectedSessionId = currentSessionId;
                  const selectedEpoch = attachmentEpochRef.current;
                  void (async () => {
                    try {
                      const register = isMockMode()
                        ? mockRegisterServerFileAttachment
                        : registerServerFileAttachment;
                      if (!selectedSessionId) return;
                      const registered = await register(selectedSessionId, selectedPath);
                      if (
                        activeAttachmentSessionRef.current !== selectedSessionId ||
                        attachmentEpochRef.current !== selectedEpoch
                      )
                        return;
                      const occurrenceId = attachmentId();
                      setAttachments((current) => [
                        ...current,
                        {
                          occurrenceId,
                          id: occurrenceId,
                          attachmentId: registered.attachmentId,
                          displayName: registered.displayName,
                          path: registered.path,
                          href: registered.href,
                          mimeType: registered.mimeType,
                          source: 'server_file' as const,
                          status: 'ready' as const,
                        },
                      ]);
                      setAttachmentBrowserOpen(false);
                      setAttachmentMenuOpen(false);
                      setAttachmentDirectoryError(null);
                    } catch (error) {
                      if (
                        activeAttachmentSessionRef.current !== selectedSessionId ||
                        attachmentEpochRef.current !== selectedEpoch
                      )
                        return;
                      setAttachmentDirectoryError(
                        error instanceof Error ? error.message : '服务端附件注册失败',
                      );
                    }
                  })();
                }}
              />
              {attachmentDirectoryError && (
                <p className="mt-2 text-sm text-danger" data-testid="attachment-directory-error">
                  {attachmentDirectoryError}
                </p>
              )}
            </div>
          </Modal>
          <div className="flex min-h-0 flex-1 gap-2">
            <input
              ref={clientAttachmentInputRef}
              type="file"
              multiple
              className="hidden"
              data-testid="client-attachment-input"
              aria-label="选择客户端附件（系统文件选择器）"
              onChange={handleClientFiles}
            />
            <textarea
              ref={inputRef}
              id="chatInput"
              placeholder="Type a message... (Enter to send, Shift+Enter for newline)"
              value={composerText}
              tabIndex={-1}
              aria-hidden="true"
              className="pointer-events-none absolute h-px w-px opacity-0"
              onChange={(e) => {
                const text = e.target.value;
                composerValueRef.current = {
                  parts: text ? [{ type: 'text', value: text }] : [{ type: 'text', value: '' }],
                  text,
                  occurrenceIds: [],
                  attachmentIds: [],
                };
                setComposerText(text);
                composerRef.current?.replaceText(text);
                if (currentSessionId) setInputDraft(currentSessionId, text);
              }}
              onKeyDown={handleKeyDown}
            />
            <RichTextComposer
              key={currentSessionId || 'no-session'}
              ref={composerRef}
              initialText={composerText}
              attachments={attachments.map(
                ({
                  id,
                  occurrenceId,
                  attachmentId: resourceAttachmentId,
                  displayName,
                  href,
                  path,
                  location,
                }) => ({
                  id,
                  occurrenceId,
                  attachmentId: resourceAttachmentId,
                  displayName,
                  href,
                  path,
                  location,
                }),
              )}
              sessionId={currentSessionId || undefined}
              onChange={handleComposerChange}
              onAttachmentDrop={handleAttachmentDrop}
              onNativeFiles={handleNativeFiles}
              onNativeInputIssue={handleNativeInputIssue}
              onRemoveAttachment={handleRemoveComposerAttachment}
              onKeyDown={handleKeyDown}
            />
            <div className="flex flex-col gap-1 items-end">
              {canSteer && (
                <button
                  onClick={() => handleSteer(composerValueRef.current.text)}
                  className="inline-flex items-center gap-1 rounded border border-accent/50 bg-accent/10 px-2 py-1 text-xs font-medium text-accent hover:bg-accent/20 transition-colors"
                  title="Send an instruction to the running Codex turn"
                >
                  <CornerUpRight size={13} />
                  Steer
                </button>
              )}
              <div className="flex items-center gap-1">
                <button
                  type="button"
                  onClick={() => handleSend(composerValueRef.current.text)}
                  disabled={attachmentsBlocked}
                  title={attachmentsBlocked ? '请等待附件上传完成，或重试/取消失败附件' : 'Send'}
                  className="rounded bg-accent px-4 py-2 text-sm font-medium text-white hover:bg-accent-hover transition-colors self-end disabled:cursor-not-allowed disabled:opacity-50"
                >
                  Send
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
